TOKEN = 'PLACE YOUR TELEGRAM BOT TOKEN'
API_URL = 'https://porfirevich.ru/api/story/?orderBy=RAND()&limit=1'
DEEP_LN_URL = 'https://crimson-flower-a705.koval.workers.dev'
QUOTES_API_URL = 'https://citaty.info/random'
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.3 Safari/537.36'
LOGGING_CONFIG = u'%(filename)+13s [ LINE:%(lineno)-4s] %(levelname)-8s [%(asctime)s] %(message)s'
